.TH "PNM_t" 3 "Mon Feb 15 2021" "Version 1.0" "Projet 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PNM_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmagicNumber\fP"
.br
.ti -1c
.RI "int \fBcolumns\fP"
.br
.ti -1c
.RI "int \fBrows\fP"
.br
.ti -1c
.RI "int \fBmaxValuePixel\fP"
.br
.ti -1c
.RI "int ** \fBmatrix\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
pnm\&.c
.PP
Ce fichier contient les définitions de types et les fonctions de manipulation d'images PNM\&.
.PP
\fBAuthor\fP
.RS 4
: Dumoulin Peissone S193957 
.RE
.PP
\fBDate\fP
.RS 4
: 22/02/21 @projet: INFO0030 Projet 1 Définition du type opaque PNM 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Projet 1 from the source code\&.
